-- AlterEnum
ALTER TYPE "FeedbackSource" ADD VALUE IF NOT EXISTS 'LISTING_REPORT';
ALTER TYPE "FeedbackSource" ADD VALUE IF NOT EXISTS 'ACCOUNT_FEEDBACK';

-- AlterEnum
ALTER TYPE "FeedbackStatus" ADD VALUE IF NOT EXISTS 'WAITING_LISTING_OWNER';
