export enum AdminPermission {
  ADMIN_PANEL_ACCESS = 'ADMIN_PANEL_ACCESS',
  USER_MANAGE = 'USER_MANAGE',
  USER_MESSAGE = 'USER_MESSAGE',
  LISTING_MODERATE = 'LISTING_MODERATE',
  VEHICLE_DATA_READ = 'VEHICLE_DATA_READ',
  VEHICLE_DATA_WRITE = 'VEHICLE_DATA_WRITE',
  VEHICLE_DATA_DELETE = 'VEHICLE_DATA_DELETE',
  GUIDE_MANAGE = 'GUIDE_MANAGE',
  AI_OPERATIONS_VIEW = 'AI_OPERATIONS_VIEW',
  FINANCE_VIEW = 'FINANCE_VIEW',
  CLUB_MODERATE = 'CLUB_MODERATE',
  ROLE_MANAGE = 'ROLE_MANAGE',
  AUDIT_VIEW = 'AUDIT_VIEW',
}

export const ALL_ADMIN_PERMISSIONS = Object.values(AdminPermission);

export const DEFAULT_ROLE_PERMISSIONS: Record<string, AdminPermission[]> = {
  SUPER_ADMIN: ALL_ADMIN_PERMISSIONS,
  ADMIN: ALL_ADMIN_PERMISSIONS.filter((p) => p !== AdminPermission.ROLE_MANAGE),
  MODERATOR: [
    AdminPermission.ADMIN_PANEL_ACCESS,
    AdminPermission.LISTING_MODERATE,
    AdminPermission.CLUB_MODERATE,
    AdminPermission.VEHICLE_DATA_READ,
  ],
};
