import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const futureExpiry = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000);

const providersData = [
  // --- SUBARU SHOWCASE (VITRIN) MEMBERS ---
  {
    isicepteProviderId: 'IC-PROV-SUBATECH',
    businessName: 'SubaTech Garage',
    slug: 'subatech-garage',
    coverImageUrl: 'https://images.unsplash.com/photo-1613214149922-f1809c99b414?auto=format&fit=crop&w=1200&q=80',
    avatarUrl: 'https://images.unsplash.com/photo-1613214149922-f1809c99b414?auto=format&fit=crop&w=400&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'İstanbul',
    district: 'Ataşehir',
    address: 'Ferhatpaşa Mah. Üsküdar Cd. No:142/A Ataşehir, İstanbul',
    phone: '+90 216 577 42 18',
    email: 'info@subatech.com.tr',
    isicepteProfileUrl: 'https://isicepte.com/usta/subatech-garage',
    supportedBrands: ['Subaru', 'Toyota', 'Honda'],
    serviceCategories: ['Motor/Mekanik', 'Oto Elektrik/Elektronik', 'Oto Ekspertiz'],
    rating: 4.8,
    reviewCount: 37,
    isShowcaseActive: true,
    showcaseStartsAt: new Date('2025-01-01'),
    showcaseExpiresAt: futureExpiry,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
  {
    isicepteProviderId: 'IC-PROV-BURSA-BOXER',
    businessName: 'Bursa Boxer Servis',
    slug: 'bursa-boxer-servis',
    coverImageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80',
    avatarUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=400&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'Bursa',
    district: 'Nilüfer',
    address: 'Üçevler Mah. Otomobilciler Sanayi Sitesi 12. Blok No:4 Nilüfer, Bursa',
    phone: '+90 224 441 16 00',
    email: 'bursa@boxerservis.com',
    isicepteProfileUrl: 'https://isicepte.com/usta/bursa-boxer-servis',
    supportedBrands: ['Subaru', 'Toyota'],
    serviceCategories: ['Motor/Mekanik', 'Oto Elektrik/Elektronik', 'Oto Yedek Parça'],
    rating: 4.9,
    reviewCount: 52,
    isShowcaseActive: true,
    showcaseStartsAt: new Date('2025-01-01'),
    showcaseExpiresAt: futureExpiry,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
  {
    isicepteProviderId: 'IC-PROV-ATASEHIR-SUBARU',
    businessName: 'Ataşehir Subaru Özel Servis',
    slug: 'atasehir-subaru-ozel-servis',
    coverImageUrl: 'https://images.unsplash.com/photo-1625047509168-a7026f36de04?auto=format&fit=crop&w=1200&q=80',
    avatarUrl: 'https://images.unsplash.com/photo-1625047509168-a7026f36de04?auto=format&fit=crop&w=400&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'İstanbul',
    district: 'Ataşehir',
    address: 'İçerenköy Mah. Bostancı Sanayi Sitesi 3. Sokak No:18 Ataşehir, İstanbul',
    phone: '+90 216 574 33 22',
    email: 'iletisim@atasehirsubaru.com',
    isicepteProfileUrl: 'https://isicepte.com/usta/atasehir-subaru-ozel-servis',
    supportedBrands: ['Subaru'],
    serviceCategories: ['Motor/Mekanik', 'Kaporta/Boya', 'Lastik/Jant'],
    rating: 4.7,
    reviewCount: 28,
    isShowcaseActive: true,
    showcaseStartsAt: new Date('2025-01-01'),
    showcaseExpiresAt: futureExpiry,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
  {
    isicepteProviderId: 'IC-PROV-ANADOLU-OTO',
    businessName: 'Anadolu Oto Elektrik',
    slug: 'anadolu-oto-elektrik',
    coverImageUrl: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=1200&q=80',
    avatarUrl: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=400&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'Ankara',
    district: 'Çankaya',
    address: 'Şaşmaz Oto Sanayi Sitesi 2. Cadde No:45 Çankaya, Ankara',
    phone: '+90 312 278 12 34',
    email: 'anadolu@otoelektrik.com',
    isicepteProfileUrl: 'https://isicepte.com/usta/anadolu-oto-elektrik',
    supportedBrands: ['Subaru', 'Honda', 'Hyundai', 'Volkswagen'],
    serviceCategories: ['Oto Elektrik/Elektronik', 'Oto Aksesuar', 'Oto Yedek Parça'],
    rating: 4.8,
    reviewCount: 19,
    isShowcaseActive: true,
    showcaseStartsAt: new Date('2025-01-01'),
    showcaseExpiresAt: futureExpiry,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
  {
    isicepteProviderId: 'IC-PROV-DETAILCRAFT',
    businessName: 'DetailCraft Garage',
    slug: 'detailcraft-garage',
    coverImageUrl: 'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&w=1200&q=80',
    avatarUrl: 'https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?auto=format&fit=crop&w=400&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'İzmir',
    district: 'Bornova',
    address: '3. Sanayi Sitesi 401. Sokak No:8 Bornova, İzmir',
    phone: '+90 232 342 90 80',
    email: 'info@detailcraft.com',
    isicepteProfileUrl: 'https://isicepte.com/usta/detailcraft-garage',
    supportedBrands: ['Subaru', 'BMW', 'Audi', 'Mercedes-Benz'],
    serviceCategories: ['Oto Yıkama & Detay', 'Cam Filmi/Kaplama', 'Oto Aksesuar'],
    rating: 4.6,
    reviewCount: 24,
    isShowcaseActive: true,
    showcaseStartsAt: new Date('2025-01-01'),
    showcaseExpiresAt: futureExpiry,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },

  // --- KOCAELI NORMAL (STANDARD) MEMBERS (ACCEPTANCE 33: 0 Vitrin, 4 Normal) ---
  {
    isicepteProviderId: 'IC-PROV-KOC-JAPON',
    businessName: 'Kocaeli Japon Oto',
    slug: 'kocaeli-japon-oto',
    coverImageUrl: 'https://images.unsplash.com/photo-1613214149922-f1809c99b414?auto=format&fit=crop&w=1200&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'Kocaeli',
    district: 'İzmit',
    address: 'Körfez Sanayi Sitesi 14. Blok No:22 İzmit, Kocaeli',
    phone: '+90 262 335 12 12',
    isicepteProfileUrl: 'https://isicepte.com/usta/kocaeli-japon-oto',
    supportedBrands: ['Subaru', 'Toyota', 'Honda'],
    serviceCategories: ['Motor/Mekanik', 'Oto Elektrik/Elektronik'],
    rating: 4.8,
    reviewCount: 31,
    isShowcaseActive: false,
    showcaseStartsAt: null,
    showcaseExpiresAt: null,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
  {
    isicepteProviderId: 'IC-PROV-KOC-ASYA',
    businessName: 'İzmit Asya & Subaru Servisi',
    slug: 'izmit-asya-subaru-servisi',
    coverImageUrl: 'https://images.unsplash.com/photo-1625047509168-a7026f36de04?auto=format&fit=crop&w=1200&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'Kocaeli',
    district: 'İzmit',
    address: 'Sanayi Mah. Ömer Türkçakal Blv. No:88 İzmit, Kocaeli',
    phone: '+90 262 331 44 55',
    isicepteProfileUrl: 'https://isicepte.com/usta/izmit-asya-subaru-servisi',
    supportedBrands: ['Subaru', 'Mitsubishi'],
    serviceCategories: ['Motor/Mekanik', 'Kaporta/Boya'],
    rating: 4.7,
    reviewCount: 18,
    isShowcaseActive: false,
    showcaseStartsAt: null,
    showcaseExpiresAt: null,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
  {
    isicepteProviderId: 'IC-PROV-KOC-KORFEZ',
    businessName: 'Körfez Otomotiv Servis',
    slug: 'korfez-otomotiv-servis',
    coverImageUrl: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=1200&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'Kocaeli',
    district: 'Körfez',
    address: 'Kuzey Mah. Cahit Zarifoğlu Cad. No:15 Körfez, Kocaeli',
    phone: '+90 262 528 77 88',
    isicepteProfileUrl: 'https://isicepte.com/usta/korfez-otomotiv-servis',
    supportedBrands: ['Subaru', 'Toyota', 'Nissan'],
    serviceCategories: ['Oto Elektrik/Elektronik', 'Lastik/Jant'],
    rating: 4.6,
    reviewCount: 14,
    isShowcaseActive: false,
    showcaseStartsAt: null,
    showcaseExpiresAt: null,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
  {
    isicepteProviderId: 'IC-PROV-KOC-GEBZE',
    businessName: 'Gebze Teknik Oto',
    slug: 'gebze-teknik-oto',
    coverImageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'Kocaeli',
    district: 'Gebze',
    address: 'Gebze Küçük Sanayi Sitesi 1184. Sok. No:7 Gebze, Kocaeli',
    phone: '+90 262 646 99 00',
    isicepteProfileUrl: 'https://isicepte.com/usta/gebze-teknik-oto',
    supportedBrands: ['Subaru', 'Honda', 'Mazda'],
    serviceCategories: ['Motor/Mekanik', 'Oto Ekspertiz'],
    rating: 4.9,
    reviewCount: 42,
    isShowcaseActive: false,
    showcaseStartsAt: null,
    showcaseExpiresAt: null,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },

  // --- POPULAR BRANDS NATIONWIDE (BMW, Mercedes, Volkswagen, Renault, Fiat, Ford) ---
  {
    isicepteProviderId: 'IC-PROV-BAVARIA-IST',
    businessName: 'Bavaria Garage',
    slug: 'bavaria-garage-istanbul',
    coverImageUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'İstanbul',
    district: 'Maslak',
    address: 'Atatürk Oto Sanayi Sitesi 2. Kısım 34. Sokak No:1408 Maslak, İstanbul',
    phone: '+90 212 285 40 50',
    isicepteProfileUrl: 'https://isicepte.com/usta/bavaria-garage',
    supportedBrands: ['BMW', 'MINI'],
    serviceCategories: ['Motor/Mekanik', 'Oto Elektrik/Elektronik', 'Oto Ekspertiz'],
    rating: 4.9,
    reviewCount: 148,
    isShowcaseActive: true,
    showcaseStartsAt: new Date('2025-01-01'),
    showcaseExpiresAt: futureExpiry,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
  {
    isicepteProviderId: 'IC-PROV-MERC-YILDIZ',
    businessName: 'Yıldız Mercedes Özel Servisi',
    slug: 'yildiz-mercedes-ozel-servisi',
    coverImageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'İstanbul',
    district: 'Ümraniye',
    address: 'Dudullu Organize Sanayi Sitesi DES Sanayi Sitesi B Blok No:12 Ümraniye, İstanbul',
    phone: '+90 216 499 70 80',
    isicepteProfileUrl: 'https://isicepte.com/usta/yildiz-mercedes-ozel-servisi',
    supportedBrands: ['Mercedes-Benz'],
    serviceCategories: ['Motor/Mekanik', 'Oto Elektrik/Elektronik'],
    rating: 4.8,
    reviewCount: 96,
    isShowcaseActive: true,
    showcaseStartsAt: new Date('2025-01-01'),
    showcaseExpiresAt: futureExpiry,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
  {
    isicepteProviderId: 'IC-PROV-VAG-TECH',
    businessName: 'VAG Tech Center',
    slug: 'vag-tech-center',
    coverImageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'Ankara',
    district: 'Yenimahalle',
    address: 'İvedik Organize Sanayi Bölgesi 1354. Cadde No:67 Yenimahalle, Ankara',
    phone: '+90 312 395 11 22',
    isicepteProfileUrl: 'https://isicepte.com/usta/vag-tech-center',
    supportedBrands: ['Volkswagen', 'Audi', 'SEAT', 'Skoda'],
    serviceCategories: ['Motor/Mekanik', 'Oto Elektrik/Elektronik', 'Oto Yedek Parça'],
    rating: 4.8,
    reviewCount: 112,
    isShowcaseActive: true,
    showcaseStartsAt: new Date('2025-01-01'),
    showcaseExpiresAt: futureExpiry,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
  {
    isicepteProviderId: 'IC-PROV-RENAULT-PRO',
    businessName: 'Akdeniz Renault & Dacia Özel Servis',
    slug: 'akdeniz-renault-dacia-servis',
    coverImageUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    membershipStatus: 'ACTIVE',
    isAutomotive: true,
    torqueScoutOptIn: true,
    countryCode: 'TR',
    city: 'Antalya',
    district: 'Kepez',
    address: 'Akdeniz Sanayi Sitesi 5005. Sokak No:31 Kepez, Antalya',
    phone: '+90 242 221 45 60',
    isicepteProfileUrl: 'https://isicepte.com/usta/akdeniz-renault-dacia-servis',
    supportedBrands: ['Renault', 'Dacia', 'Fiat'],
    serviceCategories: ['Motor/Mekanik', 'Kaporta/Boya', 'Periyodik Bakım' as any],
    rating: 4.7,
    reviewCount: 65,
    isShowcaseActive: true,
    showcaseStartsAt: new Date('2025-01-01'),
    showcaseExpiresAt: futureExpiry,
    showcaseSource: 'ISICEPTE_PURCHASE',
  },
];

async function seed() {
  console.log(`Seeding ${providersData.length} genuine İşiCepte providers...`);
  for (const p of providersData) {
    await prisma.isiCepteProvider.upsert({
      where: { isicepteProviderId: p.isicepteProviderId },
      update: p,
      create: p,
    });
  }
  console.log('Seeding completed successfully.');
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
