import { 
  lookupAutomotiveTransmissionTaxonomy, 
  formatCleanTransmissionName, 
  ClutchArchitectureType 
} from '@used-car-intelligence/shared';

interface VehicleTestCase {
  brand: string;
  model: string;
  engineCode: string;
  modelYear: number;
  fuelType: string;
  transmissionName: string;
  speeds?: number;
  hasTurbo?: boolean;
  isElectric?: boolean;
  isHybrid?: boolean;
  expectedClutchType: ClutchArchitectureType;
  expectedSpeeds: number;
  expectedFamily: string;
  expectedCleanName: string;
}

describe('50+ Popular Turkish Market Vehicle 8-Filter Ground Truth Matrix', () => {
  const VEHICLE_MATRIX: VehicleTestCase[] = [
    // 1-7: Hyundai & Kia
    {
      brand: 'Kia',
      model: 'Cerato',
      engineCode: '1.6 MPI',
      modelYear: 2022,
      fuelType: 'Benzin',
      transmissionName: 'Otomatik',
      speeds: 6,
      hasTurbo: false,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 6,
      expectedFamily: 'HYUNDAI 6-AT',
      expectedCleanName: '6 İleri Otomatik',
    },
    {
      brand: 'Hyundai',
      model: 'Elantra',
      engineCode: '1.6 MPI',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'Otomatik',
      speeds: 6,
      hasTurbo: false,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 6,
      expectedFamily: 'HYUNDAI 6-AT',
      expectedCleanName: '6 İleri Otomatik',
    },
    {
      brand: 'Hyundai',
      model: 'Tucson',
      engineCode: '1.6 T-GDI',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'Yarı Otomatik',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: '7DCT',
      expectedCleanName: '7 İleri DCT',
    },
    {
      brand: 'Hyundai',
      model: 'Tucson',
      engineCode: '1.6 CRDi',
      modelYear: 2020,
      fuelType: 'Dizel',
      transmissionName: 'Yarı Otomatik',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: '7DCT',
      expectedCleanName: '7 İleri DCT',
    },
    {
      brand: 'Kia',
      model: 'Sportage',
      engineCode: '1.6 T-GDI',
      modelYear: 2022,
      fuelType: 'Benzin',
      transmissionName: 'Yarı Otomatik',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: '7DCT',
      expectedCleanName: '7 İleri DCT',
    },
    {
      brand: 'Kia',
      model: 'Picanto',
      engineCode: '1.0 MPI',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'Yarı Otomatik',
      speeds: 5,
      hasTurbo: false,
      expectedClutchType: 'ROBOTIZE_TEK_KAVRAMA',
      expectedSpeeds: 5,
      expectedFamily: 'AMT',
      expectedCleanName: '5 İleri AMT Robotize',
    },
    {
      brand: 'Hyundai',
      model: 'i10',
      engineCode: '1.2 MPI',
      modelYear: 2022,
      fuelType: 'Benzin',
      transmissionName: 'Yarı Otomatik',
      speeds: 5,
      hasTurbo: false,
      expectedClutchType: 'ROBOTIZE_TEK_KAVRAMA',
      expectedSpeeds: 5,
      expectedFamily: 'AMT',
      expectedCleanName: '5 İleri AMT Robotize',
    },

    // 8-13: Toyota
    {
      brand: 'Toyota',
      model: 'Corolla',
      engineCode: '1.5 Vision',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'Multidrive S',
      speeds: 1,
      hasTurbo: false,
      expectedClutchType: 'CVT',
      expectedSpeeds: 1,
      expectedFamily: 'MULTIDRIVE S',
      expectedCleanName: 'Multidrive S (CVT)',
    },
    {
      brand: 'Toyota',
      model: 'Corolla',
      engineCode: '1.6 Valvematic',
      modelYear: 2018,
      fuelType: 'Benzin',
      transmissionName: 'Otomatik',
      speeds: 1,
      hasTurbo: false,
      expectedClutchType: 'CVT',
      expectedSpeeds: 1,
      expectedFamily: 'MULTIDRIVE S',
      expectedCleanName: 'Multidrive S (CVT)',
    },
    {
      brand: 'Toyota',
      model: 'Corolla',
      engineCode: '1.8 Hybrid',
      modelYear: 2020,
      fuelType: 'Hibrit',
      transmissionName: 'e-CVT',
      isHybrid: true,
      speeds: 1,
      expectedClutchType: 'ELEKTRONIK_PLANET_HIBRIT',
      expectedSpeeds: 1,
      expectedFamily: 'e-CVT',
      expectedCleanName: 'e-CVT',
    },
    {
      brand: 'Toyota',
      model: 'Yaris',
      engineCode: '1.5 Hybrid',
      modelYear: 2021,
      fuelType: 'Hibrit',
      transmissionName: 'e-CVT',
      isHybrid: true,
      speeds: 1,
      expectedClutchType: 'ELEKTRONIK_PLANET_HIBRIT',
      expectedSpeeds: 1,
      expectedFamily: 'e-CVT',
      expectedCleanName: 'e-CVT',
    },
    {
      brand: 'Toyota',
      model: 'C-HR',
      engineCode: '1.8 Hybrid',
      modelYear: 2020,
      fuelType: 'Hibrit',
      transmissionName: 'e-CVT',
      isHybrid: true,
      speeds: 1,
      expectedClutchType: 'ELEKTRONIK_PLANET_HIBRIT',
      expectedSpeeds: 1,
      expectedFamily: 'e-CVT',
      expectedCleanName: 'e-CVT',
    },
    {
      brand: 'Toyota',
      model: 'RAV4',
      engineCode: '2.5 Hybrid',
      modelYear: 2020,
      fuelType: 'Hibrit',
      transmissionName: 'e-CVT',
      isHybrid: true,
      speeds: 1,
      expectedClutchType: 'ELEKTRONIK_PLANET_HIBRIT',
      expectedSpeeds: 1,
      expectedFamily: 'e-CVT',
      expectedCleanName: 'e-CVT',
    },

    // 14-18: Renault
    {
      brand: 'Renault',
      model: 'Megane',
      engineCode: '1.3 TCe',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'EDC',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'ISLAK_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'EDC',
      expectedCleanName: '7 İleri EDC',
    },
    {
      brand: 'Renault',
      model: 'Megane',
      engineCode: '1.5 Blue dCi',
      modelYear: 2020,
      fuelType: 'Dizel',
      transmissionName: 'EDC',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'ISLAK_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'EDC',
      expectedCleanName: '7 İleri EDC',
    },
    {
      brand: 'Renault',
      model: 'Clio',
      engineCode: '1.0 TCe',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'X-Tronic',
      speeds: 1,
      hasTurbo: true,
      expectedClutchType: 'CVT',
      expectedSpeeds: 1,
      expectedFamily: 'X-TRONIC',
      expectedCleanName: 'X-Tronic (CVT)',
    },
    {
      brand: 'Renault',
      model: 'Clio',
      engineCode: '1.5 dCi',
      modelYear: 2016,
      fuelType: 'Dizel',
      transmissionName: 'EDC',
      speeds: 6,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 6,
      expectedFamily: 'EDC',
      expectedCleanName: '6 İleri EDC',
    },
    {
      brand: 'Renault',
      model: 'Austral',
      engineCode: '1.2 E-Tech',
      modelYear: 2023,
      fuelType: 'Hibrit',
      transmissionName: 'Otomatik',
      isHybrid: true,
      speeds: 1,
      expectedClutchType: 'ELEKTRONIK_PLANET_HIBRIT',
      expectedSpeeds: 1,
      expectedFamily: 'E-TECH',
      expectedCleanName: 'E-Tech Akıllı Çok Modlu Otomatik',
    },

    // 19-23: Fiat
    {
      brand: 'Fiat',
      model: 'Egea',
      engineCode: '1.4 Fire',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'Manuel',
      speeds: 6,
      hasTurbo: false,
      expectedClutchType: 'MANUEL',
      expectedSpeeds: 6,
      expectedFamily: 'MANUEL',
      expectedCleanName: '6 İleri Manuel',
    },
    {
      brand: 'Fiat',
      model: 'Egea',
      engineCode: '1.3 MultiJet',
      modelYear: 2020,
      fuelType: 'Dizel',
      transmissionName: 'Manuel',
      speeds: 5,
      hasTurbo: true,
      expectedClutchType: 'MANUEL',
      expectedSpeeds: 5,
      expectedFamily: 'MANUEL',
      expectedCleanName: '5 İleri Manuel',
    },
    {
      brand: 'Fiat',
      model: 'Egea',
      engineCode: '1.6 MultiJet',
      modelYear: 2020,
      fuelType: 'Dizel',
      transmissionName: 'DCT',
      speeds: 6,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 6,
      expectedFamily: 'DDCT',
      expectedCleanName: '6 İleri Kuru Çift Kavrama',
    },
    {
      brand: 'Fiat',
      model: 'Egea',
      engineCode: '1.6 E-Torq',
      modelYear: 2018,
      fuelType: 'Benzin',
      transmissionName: 'Otomatik',
      speeds: 6,
      hasTurbo: false,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 6,
      expectedFamily: 'AISIN 6-AT',
      expectedCleanName: '6 İleri Otomatik',
    },

    // 24-30: Volkswagen
    {
      brand: 'Volkswagen',
      model: 'Golf',
      engineCode: '1.0 TSI',
      modelYear: 2020,
      fuelType: 'Benzin',
      transmissionName: 'DSG',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'DSG',
      expectedCleanName: '7 İleri DSG',
    },
    {
      brand: 'Volkswagen',
      model: 'Golf',
      engineCode: '1.5 eTSI',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'DSG',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'DSG',
      expectedCleanName: '7 İleri DSG',
    },
    {
      brand: 'Volkswagen',
      model: 'Passat',
      engineCode: '1.6 TDI',
      modelYear: 2018,
      fuelType: 'Dizel',
      transmissionName: 'DSG',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'DSG',
      expectedCleanName: '7 İleri DSG',
    },
    {
      brand: 'Volkswagen',
      model: 'Passat',
      engineCode: '2.0 TDI',
      modelYear: 2019,
      fuelType: 'Dizel',
      transmissionName: 'DSG',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'ISLAK_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'DSG',
      expectedCleanName: '7 İleri DSG',
    },
    {
      brand: 'Volkswagen',
      model: 'Polo',
      engineCode: '1.0 TSI',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'DSG',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'DSG',
      expectedCleanName: '7 İleri DSG',
    },
    {
      brand: 'Volkswagen',
      model: 'Touareg',
      engineCode: '3.0 TDI',
      modelYear: 2018,
      fuelType: 'Dizel',
      transmissionName: 'Otomatik',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: 'TORK KONVERTÖRLÜ (ZF 8HP / AISIN)',
      expectedCleanName: '8 İleri Otomatik (ZF)',
    },

    // 31-35: Skoda, Seat, Audi
    {
      brand: 'Skoda',
      model: 'Octavia',
      engineCode: '1.0 e-TEC',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'DSG',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'DSG',
      expectedCleanName: '7 İleri DSG',
    },
    {
      brand: 'Skoda',
      model: 'Superb',
      engineCode: '1.5 TSI',
      modelYear: 2020,
      fuelType: 'Benzin',
      transmissionName: 'DSG',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'DSG',
      expectedCleanName: '7 İleri DSG',
    },
    {
      brand: 'Seat',
      model: 'Leon',
      engineCode: '1.5 eTSI',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'DSG',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'DSG',
      expectedCleanName: '7 İleri DSG',
    },
    {
      brand: 'Audi',
      model: 'A3',
      engineCode: '35 TFSI',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'S-Tronic',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'DSG',
      expectedCleanName: '7 İleri DSG',
    },
    {
      brand: 'Audi',
      model: 'A4',
      engineCode: '40 TDI',
      modelYear: 2020,
      fuelType: 'Dizel',
      transmissionName: 'S-Tronic',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'ISLAK_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: 'S-TRONIC',
      expectedCleanName: '7 İleri S-Tronic',
    },

    // 36-39: BMW
    {
      brand: 'BMW',
      model: '320i',
      engineCode: '1.6 B48',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'Otomatik',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: 'ZF 8HP',
      expectedCleanName: '8 İleri Otomatik (ZF)',
    },
    {
      brand: 'BMW',
      model: '520i',
      engineCode: '1.6 Turbo',
      modelYear: 2020,
      fuelType: 'Benzin',
      transmissionName: 'Otomatik',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: 'ZF 8HP',
      expectedCleanName: '8 İleri Otomatik (ZF)',
    },
    {
      brand: 'BMW',
      model: '520d',
      engineCode: '2.0 Dizel',
      modelYear: 2019,
      fuelType: 'Dizel',
      transmissionName: 'Otomatik',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: 'ZF 8HP',
      expectedCleanName: '8 İleri Otomatik (ZF)',
    },

    // 40-43: Mercedes-Benz
    {
      brand: 'Mercedes-Benz',
      model: 'C 200',
      engineCode: '1.5 M264',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: '9G-Tronic',
      speeds: 9,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 9,
      expectedFamily: '9G-TRONIC',
      expectedCleanName: '9G-Tronic Otomatik',
    },
    {
      brand: 'Mercedes-Benz',
      model: 'C 200 d',
      engineCode: '1.6 OM654',
      modelYear: 2019,
      fuelType: 'Dizel',
      transmissionName: '9G-Tronic',
      speeds: 9,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 9,
      expectedFamily: '9G-TRONIC',
      expectedCleanName: '9G-Tronic Otomatik',
    },
    {
      brand: 'Mercedes-Benz',
      model: 'A 200',
      engineCode: '1.3 M282',
      modelYear: 2020,
      fuelType: 'Benzin',
      transmissionName: '7G-DCT',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'ISLAK_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: '7G-DCT',
      expectedCleanName: '7 İleri 7G-DCT',
    },
    {
      brand: 'Mercedes-Benz',
      model: 'CLA 180 d',
      engineCode: '1.5 OM607',
      modelYear: 2016,
      fuelType: 'Dizel',
      transmissionName: '7G-DCT',
      speeds: 7,
      hasTurbo: true,
      expectedClutchType: 'ISLAK_CIFT_KAVRAMA',
      expectedSpeeds: 7,
      expectedFamily: '7G-DCT',
      expectedCleanName: '7 İleri 7G-DCT',
    },

    // 44-50: Stellantis (Peugeot, Citroen, Opel)
    {
      brand: 'Peugeot',
      model: '3008',
      engineCode: '1.5 BlueHDi',
      modelYear: 2021,
      fuelType: 'Dizel',
      transmissionName: 'EAT8',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: 'EAT8',
      expectedCleanName: '8 İleri Otomatik (EAT8)',
    },
    {
      brand: 'Peugeot',
      model: '2008',
      engineCode: '1.2 PureTech',
      modelYear: 2022,
      fuelType: 'Benzin',
      transmissionName: 'EAT8',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: 'EAT8',
      expectedCleanName: '8 İleri Otomatik (EAT8)',
    },
    {
      brand: 'Peugeot',
      model: '508',
      engineCode: '1.6 PureTech',
      modelYear: 2020,
      fuelType: 'Benzin',
      transmissionName: 'EAT8',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: 'EAT8',
      expectedCleanName: '8 İleri Otomatik (EAT8)',
    },
    {
      brand: 'Citroen',
      model: 'C5 Aircross',
      engineCode: '1.5 BlueHDi',
      modelYear: 2021,
      fuelType: 'Dizel',
      transmissionName: 'EAT8',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: 'EAT8',
      expectedCleanName: '8 İleri Otomatik (EAT8)',
    },
    {
      brand: 'Citroen',
      model: 'C3 Aircross',
      engineCode: '1.2 PureTech',
      modelYear: 2019,
      fuelType: 'Benzin',
      transmissionName: 'EAT6',
      speeds: 6,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 6,
      expectedFamily: 'EAT6',
      expectedCleanName: '6 İleri Otomatik (EAT6)',
    },
    {
      brand: 'Opel',
      model: 'Corsa',
      engineCode: '1.2 Turbo',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'EAT8',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: 'EAT8',
      expectedCleanName: '8 İleri Otomatik (EAT8)',
    },
    {
      brand: 'Opel',
      model: 'Astra',
      engineCode: '1.2 Turbo',
      modelYear: 2022,
      fuelType: 'Benzin',
      transmissionName: 'EAT8',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: 'EAT8',
      expectedCleanName: '8 İleri Otomatik (EAT8)',
    },

    // 51-54: Ford
    {
      brand: 'Ford',
      model: 'Focus',
      engineCode: '1.5 EcoBlue',
      modelYear: 2020,
      fuelType: 'Dizel',
      transmissionName: 'Otomatik',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: '8F35',
      expectedCleanName: '8 İleri Otomatik',
    },
    {
      brand: 'Ford',
      model: 'Focus',
      engineCode: '1.6 Ti-VCT',
      modelYear: 2013,
      fuelType: 'Benzin',
      transmissionName: 'Powershift',
      speeds: 6,
      hasTurbo: false,
      expectedClutchType: 'KURU_CIFT_KAVRAMA',
      expectedSpeeds: 6,
      expectedFamily: 'POWERSHIFT',
      expectedCleanName: '6 İleri Powershift',
    },
    {
      brand: 'Ford',
      model: 'Kuga',
      engineCode: '1.5 EcoBlue',
      modelYear: 2021,
      fuelType: 'Dizel',
      transmissionName: 'Otomatik',
      speeds: 8,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 8,
      expectedFamily: '8F35',
      expectedCleanName: '8 İleri Otomatik',
    },

    // 55-57: Nissan & Honda
    {
      brand: 'Nissan',
      model: 'Qashqai',
      engineCode: '1.3 DIG-T',
      modelYear: 2021,
      fuelType: 'Benzin',
      transmissionName: 'X-Tronic',
      speeds: 1,
      hasTurbo: true,
      expectedClutchType: 'CVT',
      expectedSpeeds: 1,
      expectedFamily: 'X-TRONIC',
      expectedCleanName: 'X-Tronic (CVT)',
    },
    {
      brand: 'Honda',
      model: 'Civic',
      engineCode: '1.5 VTEC',
      modelYear: 2020,
      fuelType: 'Benzin',
      transmissionName: 'CVT',
      speeds: 1,
      hasTurbo: true,
      expectedClutchType: 'CVT',
      expectedSpeeds: 1,
      expectedFamily: 'CVT',
      expectedCleanName: 'Kademesiz Otomatik (CVT)',
    },
    {
      brand: 'Honda',
      model: 'Civic',
      engineCode: '1.6 i-DTEC',
      modelYear: 2019,
      fuelType: 'Dizel',
      transmissionName: 'Otomatik',
      speeds: 9,
      hasTurbo: true,
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 9,
      expectedFamily: 'ZF 9HP',
      expectedCleanName: '9 İleri Otomatik (ZF)',
    },

    // 58-61: Electric Vehicles (BEV)
    {
      brand: 'Tesla',
      model: 'Model 3',
      engineCode: 'Dual Motor',
      modelYear: 2023,
      fuelType: 'Elektrik',
      transmissionName: 'Otomatik',
      isElectric: true,
      speeds: 1,
      expectedClutchType: 'ELEKTRIKLI_TEK_ORANLI',
      expectedSpeeds: 1,
      expectedFamily: 'REDÜKTÖR',
      expectedCleanName: 'Doğrudan Tahrikli (Tek Vites)',
    },
    {
      brand: 'Tesla',
      model: 'Model Y',
      engineCode: 'Long Range',
      modelYear: 2023,
      fuelType: 'Elektrik',
      transmissionName: 'Otomatik',
      isElectric: true,
      speeds: 1,
      expectedClutchType: 'ELEKTRIKLI_TEK_ORANLI',
      expectedSpeeds: 1,
      expectedFamily: 'REDÜKTÖR',
      expectedCleanName: 'Doğrudan Tahrikli (Tek Vites)',
    },
    {
      brand: 'Togg',
      model: 'T10X',
      engineCode: 'V2 RWD',
      modelYear: 2023,
      fuelType: 'Elektrik',
      transmissionName: 'Otomatik',
      isElectric: true,
      speeds: 1,
      expectedClutchType: 'ELEKTRIKLI_TEK_ORANLI',
      expectedSpeeds: 1,
      expectedFamily: 'REDÜKTÖR',
      expectedCleanName: 'Doğrudan Tahrikli (Tek Vites)',
    },
    {
      brand: 'BYD',
      model: 'Atto 3',
      engineCode: 'Design',
      modelYear: 2023,
      fuelType: 'Elektrik',
      transmissionName: 'Otomatik',
      isElectric: true,
      speeds: 1,
      expectedClutchType: 'ELEKTRIKLI_TEK_ORANLI',
      expectedSpeeds: 1,
      expectedFamily: 'REDÜKTÖR',
      expectedCleanName: 'Doğrudan Tahrikli (Tek Vites)',
    },
    {
      brand: 'Subaru',
      model: 'Impreza',
      engineCode: '2.0',
      modelYear: 2006,
      fuelType: 'Benzin',
      transmissionName: 'Otomatik',
      expectedClutchType: 'TORK_KONVERTORLU',
      expectedSpeeds: 4,
      expectedFamily: 'SUBARU 4EAT',
      expectedCleanName: '4 İleri Otomatik',
    },
    {
      brand: 'Subaru',
      model: 'Impreza',
      engineCode: '2.0',
      modelYear: 2012,
      fuelType: 'Benzin',
      transmissionName: 'Otomatik',
      expectedClutchType: 'CVT',
      expectedSpeeds: 1,
      expectedFamily: 'LINEARTRONIC CVT',
      expectedCleanName: 'Lineartronic (CVT)',
    },
  ];

  it('contains at least 50 comprehensive vehicle test cases', () => {
    expect(VEHICLE_MATRIX.length).toBeGreaterThanOrEqual(50);
  });

  describe.each(VEHICLE_MATRIX)(
    '$modelYear $brand $model ($engineCode - $transmissionName)',
    (tc) => {
      it(`resolves correctly to ${tc.expectedFamily} (${tc.expectedClutchType}) without internal codes`, () => {
        const result = lookupAutomotiveTransmissionTaxonomy({
          brand: tc.brand,
          model: tc.model,
          engineCode: tc.engineCode,
          modelYear: tc.modelYear,
          fuelType: tc.fuelType,
          transmissionName: tc.transmissionName,
          speeds: tc.speeds,
          hasTurbo: tc.hasTurbo,
          isElectric: tc.isElectric,
          isHybrid: tc.isHybrid,
        });

        // 1. Check Clutch Type Fidelity
        expect(result.clutchType).toBe(tc.expectedClutchType);

        // 2. Check Speed Count Fidelity
        expect(result.transmissionSpeeds).toBe(tc.expectedSpeeds);

        // 3. Check Transmission Family
        expect(result.transmissionFamily).toBe(tc.expectedFamily);

        // 4. Check Clean Display Name Formatting
        const cleanName = formatCleanTransmissionName(result.transmissionTypeAndSpeeds);
        expect(cleanName).toBe(tc.expectedCleanName);

        // 5. Zero Internal Engineering Codes In Clean Header
        expect(cleanName).not.toMatch(/\((?:hyundai|aisin|getrag|zf\s*\d|dq\d+|dl\d+|d7uf|a6gf|c635|8f35)\)/i);
      });
    },
  );
});
